<pre class="shiki nord" style="background-color:#2e3440ff;color:#d8dee9ff" tabindex="0"><code><span class="line"></span>
<span class="line"><span style="color:#616E88">// WARNING: This file is auto-generated by the figma-variables-to-code plugin.</span></span>
<span class="line"><span style="color:#616E88">// DO NOT manually modify this file. Any manual changes will be overwritten </span></span>
<span class="line"><span style="color:#616E88">// during the next generation process.</span></span>
<span class="line"><span style="color:#81A1C1">import</span><span style="color:#A3BE8C"> 'dart:ui'</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">abstract</span><span style="color:#81A1C1"> final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> primitiveColors </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> PrimitiveColors</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> semanticColors </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> SemanticColors</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> numbers </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Numbers</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> typography </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Typography</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> PrimitiveColors</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> PrimitiveColors</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _grey </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Grey</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Grey</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> grey </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _grey</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _blue </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Blue</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Blue</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> blue </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _blue</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _white </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFFFFFFFF</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> white </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _white</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _black </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF000000</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> black </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _black</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _black50 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0x7F000000</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> black50 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _black50</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _red </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Red</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Red</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> red </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _red</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Grey</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Grey</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n600 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF1A1A1A</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n600 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n600</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n700 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF151515</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n700 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n700</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n300 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF323232</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n300 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n300</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n400 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF2E2E2E</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n400 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n400</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n100 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFFA6A6A6</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n100 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n100</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n200 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF7B7B7B</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n200 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n200</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n500 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF252525</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n500 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n500</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Blue</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Blue</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n500 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF0049FF</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n500 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n500</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n200 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFF7AA0FF</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n200 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n200</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Red</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Red</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n500 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFFFF200C</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n500 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n500</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n400 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFFFF5436</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n400 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n400</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n300 </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Color</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0xFFFF795B</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n300 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n300</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> SemanticColors</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> SemanticColors</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _background </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Background</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Background</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> background </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _background</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _text </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Text</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Text</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> text </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _text</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _stroke </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Stroke</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Stroke</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> stroke </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _stroke</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _buttons </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Buttons</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Buttons</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> buttons </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _buttons</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _icon </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Icon</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Icon</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> icon </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _icon</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _fill </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Fill</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Fill</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> fill </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _fill</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _progressBar </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> ProgressBar</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  ProgressBar</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> progressBar </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _progressBar</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _modal </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Modal</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Modal</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> modal </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _modal</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Background</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Background</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _bgMain </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n700</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bgMain </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bgMain</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _bgComponent </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n600</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bgComponent </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bgComponent</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _bgTag </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n300</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bgTag </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bgTag</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _bgTab </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n500</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bgTab </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bgTab</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Text</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Text</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _textPrimary </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">white</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> textPrimary </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _textPrimary</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _textSecondary </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n100</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> textSecondary </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _textSecondary</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _textError </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">red</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n300</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> textError </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _textError</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _textDisabled </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n600</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> textDisabled </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _textDisabled</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _textSupporting </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n200</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> textSupporting </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _textSupporting</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _textLink </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">blue</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n200</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> textLink </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _textLink</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _textBlue </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">blue</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n500</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> textBlue </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _textBlue</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Stroke</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Stroke</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _strokeComponent </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n400</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> strokeComponent </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _strokeComponent</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _strokeError </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">red</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n300</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> strokeError </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _strokeError</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _strokeWhite </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">white</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> strokeWhite </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _strokeWhite</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Buttons</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Buttons</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _bgPrimary </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">blue</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n500</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bgPrimary </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bgPrimary</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _bgSecondary </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n300</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bgSecondary </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bgSecondary</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _bgDisabled </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n300</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bgDisabled </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bgDisabled</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Icon</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Icon</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _iconInactive </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n200</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> iconInactive </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _iconInactive</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _iconActive </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">blue</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n500</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> iconActive </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _iconActive</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Fill</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Fill</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _fillWhite </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">white</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> fillWhite </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _fillWhite</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _fillBlack </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n700</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> fillBlack </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _fillBlack</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> ProgressBar</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> ProgressBar</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _bg </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n400</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bg </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bg</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _progress </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">blue</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n500</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> progress </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _progress</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Modal</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Modal</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _modalOverlay </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">black</span><span style="color:#81A1C1">-</span><span style="color:#B48EAD">50</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> modalOverlay </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _modalOverlay</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _modalBg </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n700</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> modalBg </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _modalBg</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _modalStroke </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FigmaVariables</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">primitiveColors</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">grey</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9FF">n300</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Color</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> modalStroke </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _modalStroke</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Numbers</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Numbers</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _spacing </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> Spacing</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  Spacing</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> spacing </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _spacing</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _fontSize </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FontSize</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  FontSize</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> fontSize </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _fontSize</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _radiusValue </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> RadiusValue</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  RadiusValue</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> radiusValue </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _radiusValue</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _lineHeight </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> LineHeight</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  LineHeight</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> lineHeight </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _lineHeight</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Spacing</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Spacing</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _xl </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 32</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> xl </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _xl</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _s </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 12</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> s </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _s</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _m </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 16</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> m </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _m</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _l </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 24</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> l </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _l</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _xs </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 8</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> xs </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _xs</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _n2xs </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 4</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n2xs </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n2xs</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _n3xs </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 2</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n3xs </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n3xs</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _n2xl </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 40</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n2xl </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n2xl</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> final</span><span style="color:#D8DEE9FF"> _n0 </span><span style="color:#81A1C1">=</span><span style="color:#81A1C1"> null;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n0 </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n0</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> FontSize</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> FontSize</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _xs </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 12</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> xs </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _xs</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _s </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 14</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> s </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _s</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _m </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 16</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> m </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _m</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _l </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 20</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> l </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _l</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _xl </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 40</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> xl </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _xl</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _n2xl </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 48</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n2xl </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n2xl</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _n3xl </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 64</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n3xl </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n3xl</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> RadiusValue</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> RadiusValue</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _s </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 8</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> s </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _s</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _m </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 12</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> m </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _m</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _l </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 100</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> l </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _l</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _xs </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 4</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> xs </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _xs</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> LineHeight</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> LineHeight</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _s </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 16</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> s </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _s</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _m </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 20</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> m </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _m</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _xl </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 40</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> xl </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _xl</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _n2xl </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 44</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n2xl </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n2xl</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _n3xl </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 56</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n3xl </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n3xl</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _l </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 24</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> l </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _l</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _xs </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 14</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> xs </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _xs</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _n2xs </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 12</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  int</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> n2xs </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _n2xs</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Typography</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> Typography</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _fontFamilyName </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FontFamilyName</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  FontFamilyName</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> fontFamilyName </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _fontFamilyName</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _fontWeightValue </span><span style="color:#81A1C1">=</span><span style="color:#8FBCBB"> FontWeightValue</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  FontWeightValue</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> fontWeightValue </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _fontWeightValue</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> FontFamilyName</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> FontFamilyName</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _title </span><span style="color:#81A1C1">=</span><span style="color:#A3BE8C"> 'Poppins'</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  String</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> title </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _title</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _body </span><span style="color:#81A1C1">=</span><span style="color:#A3BE8C"> 'Poppins'</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  String</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> body </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _body</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _display </span><span style="color:#81A1C1">=</span><span style="color:#A3BE8C"> 'Poppins'</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  String</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> display </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _display</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> FontWeightValue</span><span style="color:#D8DEE9FF"> {</span></span>
<span class="line"><span style="color:#81A1C1">  const</span><span style="color:#8FBCBB"> FontWeightValue</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _bold </span><span style="color:#81A1C1">=</span><span style="color:#A3BE8C"> 'Bold'</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  String</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> bold </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _bold</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _semibold </span><span style="color:#81A1C1">=</span><span style="color:#A3BE8C"> 'Semibold'</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  String</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> semibold </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _semibold</span><span style="color:#81A1C1">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#81A1C1">  static</span><span style="color:#81A1C1"> const</span><span style="color:#D8DEE9FF"> _regular </span><span style="color:#81A1C1">=</span><span style="color:#A3BE8C"> 'Regular'</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#8FBCBB">  String</span><span style="color:#81A1C1"> get</span><span style="color:#D8DEE9FF"> regular </span><span style="color:#81A1C1">=></span><span style="color:#D8DEE9FF"> _regular</span><span style="color:#81A1C1">;</span></span>
<span class="line"><span style="color:#D8DEE9FF">}</span></span>
<span class="line"></span></code></pre>