// WARNING: This file is auto-generated by the figma-variables-to-code plugin.
// DO NOT manually modify this file. Any manual changes will be overwritten
// during the next generation process.
import 'dart:ui';

abstract final class Variables {
  static const primitiveColors = PrimitiveColors();
  static const semanticColors = SemanticColors();
  static const numbers = Numbers();
  static const typography = Typography();
}

final class PrimitiveColors {
  const PrimitiveColors();

  static const _grey = Grey();
  Grey get grey => _grey;

  static const _blue = Blue();
  Blue get blue => _blue;

  static final _white = Color(0xFFFFFFFF);
  Color get white => _white;

  static final _black = Color(0xFF000000);
  Color get black => _black;

  static final _black50 = Color(0x7F000000);
  Color get black50 => _black50;

  static const _red = Red();
  Red get red => _red;
}

final class Grey {
  const Grey();

  static final _n600 = Color(0xFF1A1A1A);
  Color get n600 => _n600;

  static final _n700 = Color(0xFF151515);
  Color get n700 => _n700;

  static final _n300 = Color(0xFF323232);
  Color get n300 => _n300;

  static final _n400 = Color(0xFF2E2E2E);
  Color get n400 => _n400;

  static final _n100 = Color(0xFFA6A6A6);
  Color get n100 => _n100;

  static final _n200 = Color(0xFF7B7B7B);
  Color get n200 => _n200;

  static final _n500 = Color(0xFF252525);
  Color get n500 => _n500;
}

final class Blue {
  const Blue();

  static final _n500 = Color(0xFF0049FF);
  Color get n500 => _n500;

  static final _n200 = Color(0xFF7AA0FF);
  Color get n200 => _n200;
}

final class Red {
  const Red();

  static final _n500 = Color(0xFFFF200C);
  Color get n500 => _n500;

  static final _n400 = Color(0xFFFF5436);
  Color get n400 => _n400;

  static final _n300 = Color(0xFFFF795B);
  Color get n300 => _n300;
}

final class SemanticColors {
  const SemanticColors();

  static const _background = Background();
  Background get background => _background;

  static const _text = Text();
  Text get text => _text;

  static const _stroke = Stroke();
  Stroke get stroke => _stroke;

  static const _buttons = Buttons();
  Buttons get buttons => _buttons;

  static const _icon = Icon();
  Icon get icon => _icon;

  static const _fill = Fill();
  Fill get fill => _fill;

  static const _progressBar = ProgressBar();
  ProgressBar get progressBar => _progressBar;

  static const _modal = Modal();
  Modal get modal => _modal;
}

final class Background {
  const Background();

  static final _bgMain = Variables.primitiveColors.grey.n700;
  Color get bgMain => _bgMain;

  static final _bgComponent = Variables.primitiveColors.grey.n600;
  Color get bgComponent => _bgComponent;

  static final _bgTag = Variables.primitiveColors.grey.n300;
  Color get bgTag => _bgTag;

  static final _bgTab = Variables.primitiveColors.grey.n500;
  Color get bgTab => _bgTab;
}

final class Text {
  const Text();

  static final _textPrimary = Variables.primitiveColors.white;
  Color get textPrimary => _textPrimary;

  static final _textSecondary = Variables.primitiveColors.grey.n100;
  Color get textSecondary => _textSecondary;

  static final _textError = Variables.primitiveColors.red.n300;
  Color get textError => _textError;

  static final _textDisabled = Variables.primitiveColors.grey.n600;
  Color get textDisabled => _textDisabled;

  static final _textSupporting = Variables.primitiveColors.grey.n200;
  Color get textSupporting => _textSupporting;

  static final _textLink = Variables.primitiveColors.blue.n200;
  Color get textLink => _textLink;

  static final _textBlue = Variables.primitiveColors.blue.n500;
  Color get textBlue => _textBlue;
}

final class Stroke {
  const Stroke();

  static final _strokeComponent = Variables.primitiveColors.grey.n400;
  Color get strokeComponent => _strokeComponent;

  static final _strokeError = Variables.primitiveColors.red.n300;
  Color get strokeError => _strokeError;

  static final _strokeWhite = Variables.primitiveColors.white;
  Color get strokeWhite => _strokeWhite;
}

final class Buttons {
  const Buttons();

  static final _bgPrimary = Variables.primitiveColors.blue.n500;
  Color get bgPrimary => _bgPrimary;

  static final _bgSecondary = Variables.primitiveColors.grey.n300;
  Color get bgSecondary => _bgSecondary;

  static final _bgDisabled = Variables.primitiveColors.grey.n300;
  Color get bgDisabled => _bgDisabled;
}

final class Icon {
  const Icon();

  static final _iconInactive = Variables.primitiveColors.grey.n200;
  Color get iconInactive => _iconInactive;

  static final _iconActive = Variables.primitiveColors.blue.n500;
  Color get iconActive => _iconActive;
}

final class Fill {
  const Fill();

  static final _fillWhite = Variables.primitiveColors.white;
  Color get fillWhite => _fillWhite;

  static final _fillBlack = Variables.primitiveColors.grey.n700;
  Color get fillBlack => _fillBlack;
}

final class ProgressBar {
  const ProgressBar();

  static final _bg = Variables.primitiveColors.grey.n400;
  Color get bg => _bg;

  static final _progress = Variables.primitiveColors.blue.n500;
  Color get progress => _progress;
}

final class Modal {
  const Modal();

  static final _modalOverlay = Variables.primitiveColors.black50;
  Color get modalOverlay => _modalOverlay;

  static final _modalBg = Variables.primitiveColors.grey.n700;
  Color get modalBg => _modalBg;

  static final _modalStroke = Variables.primitiveColors.grey.n300;
  Color get modalStroke => _modalStroke;
}

final class Numbers {
  const Numbers();

  static const _spacing = Spacing();
  Spacing get spacing => _spacing;

  static const _fontSize = FontSize();
  FontSize get fontSize => _fontSize;

  static const _radiusValue = RadiusValue();
  RadiusValue get radiusValue => _radiusValue;

  static const _lineHeight = LineHeight();
  LineHeight get lineHeight => _lineHeight;
}

final class Spacing {
  const Spacing();

  static const _xl = 32;
  int get xl => _xl;

  static const _s = 12;
  int get s => _s;

  static const _m = 16;
  int get m => _m;

  static const _l = 24;
  int get l => _l;

  static const _xs = 8;
  int get xs => _xs;

  static const _n2xs = 4;
  int get n2xs => _n2xs;

  static const _n3xs = 2;
  int get n3xs => _n3xs;

  static const _n2xl = 40;
  int get n2xl => _n2xl;

  static const _n0 = 0;
  int get n0 => _n0;
}

final class FontSize {
  const FontSize();

  static const _xs = 12;
  int get xs => _xs;

  static const _s = 14;
  int get s => _s;

  static const _m = 16;
  int get m => _m;

  static const _l = 20;
  int get l => _l;

  static const _xl = 40;
  int get xl => _xl;

  static const _n2xl = 48;
  int get n2xl => _n2xl;

  static const _n3xl = 64;
  int get n3xl => _n3xl;
}

final class RadiusValue {
  const RadiusValue();

  static const _s = 8;
  int get s => _s;

  static const _m = 12;
  int get m => _m;

  static const _l = 100;
  int get l => _l;

  static const _xs = 4;
  int get xs => _xs;
}

final class LineHeight {
  const LineHeight();

  static const _s = 16;
  int get s => _s;

  static const _m = 20;
  int get m => _m;

  static const _xl = 40;
  int get xl => _xl;

  static const _n2xl = 44;
  int get n2xl => _n2xl;

  static const _n3xl = 56;
  int get n3xl => _n3xl;

  static const _l = 24;
  int get l => _l;

  static const _xs = 14;
  int get xs => _xs;

  static const _n2xs = 12;
  int get n2xs => _n2xs;
}

final class Typography {
  const Typography();

  static const _fontFamilyName = FontFamilyName();
  FontFamilyName get fontFamilyName => _fontFamilyName;

  static const _fontWeightValue = FontWeightValue();
  FontWeightValue get fontWeightValue => _fontWeightValue;
}

final class FontFamilyName {
  const FontFamilyName();

  static const _title = 'Poppins';
  String get title => _title;

  static const _body = 'Poppins';
  String get body => _body;

  static const _display = 'Poppins';
  String get display => _display;
}

final class FontWeightValue {
  const FontWeightValue();

  static const _bold = 'Bold';
  String get bold => _bold;

  static const _semibold = 'Semibold';
  String get semibold => _semibold;

  static const _regular = 'Regular';
  String get regular => _regular;
}
